### ISSUE TITLE
Create an SSH key and add it to GitHub account

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-Rudya93#3]
See:
* https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/#generating-a-new-ssh-key (you may omit adding a password)
* https://help.github.com/articles/connecting-to-github-with-ssh/

After completing instructions, post the result of the following command in a comment to this issue:
```shell
ssh -T git@github.com
```

**Comment by Rudya93** [comment]
The authenticity of host 'github.com (140.82.118.4)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,140.82.118.4' (RSA) to the list of known hosts.
Hi Rudya93! You've successfully authenticated, but GitHub does not provide shell access.
